name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run only critical tests
      - name: Run Critical Tests
        id: run-tests
        run: |
          mvn test -DsuiteXmlFile=critical-tests.xml | tee maven.log
          echo "exit_code=${PIPESTATUS[0]}" >> $GITHUB_ENV

      # Step 5: Parse failing tests
      - name: Parse failing tests
        if: always()
        id: parse-failures
        run: |
          mkdir -p test-results
          grep -H "<testcase" target/surefire-reports/*.xml | grep 'failure' | \
          sed -E 's/.*classname="([^"]+)".*name="([^"]+)".*/\1.\2/' > test-results/failures.txt || true
          echo "failures=$(cat test-results/failures.txt)" >> $GITHUB_OUTPUT

      # Step 6: Send email if there are failures
      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ GalaxyAutomation CI/CD Test Failure"
          body: |
            The following tests failed in GalaxyAutomation_login_POSTING_FILE:

            ${{ steps.parse-failures.outputs.failures }}

            
          to: Salah.Mohamed@paysky.io
          from: eslam.samy@paysky.io
